version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=microservices_project
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=27017
    networks:
      - services-network

  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=microservices_project
    networks:
      - services-network
  
networks:
  services-network:
    external: true
